language: php
php:
  - '5.4.45'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
os:
  - linux
matrix:
  include:
    - php: 5.3
      dist: precise
before_install:
  - composer self-update
  - composer install

script: phpunit --verbose --debug
